// Auto-generated by: cd backend && pnpm db:types
// Run after changing your Supabase schema to regenerate this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = Record<string, never>
